In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
# Q1. Pandas version
pd.__version__

'3.0.5'

In [5]:
# Q2. Records count
df.shape

(10000, 11)

In [6]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [7]:
# Q3. Fuel types
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [8]:
#4. Missing values
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# Q5. Max fuel efficiency
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [10]:
# Q6. Median value of horsepower
print(df['horsepower'].median())
print(df['horsepower'].mode().iloc[0])

254.0
252.0

In [16]:
mode_val = df['horsepower'].mode()
df['horsepower'] = df['horsepower'].fillna(mode_val.iloc[0])

In [18]:
print(df['horsepower'].isnull().sum())
print(df['horsepower'].median())

0
252.0

In [19]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [20]:
df_asia = df[df['origin'] == 'Asia']
df_asia[['vehicle_weight','model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [21]:
import numpy as np

In [ ]:
X=df_asia[['vehicle_weight','model_year']].head(7).to_numpy()

In [28]:
print(X)
print(X.T)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]

In [33]:
XTX = X.T@X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [35]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [36]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [37]:
w = XTX_inv@X.T@y

In [38]:
w

array([0.13644777, 0.2327492 ])

In [40]:
w.sum()

np.float64(0.36919696904925486)